config/routes.rb
city_constraint = Proc.new do |req|
  city = req.params[:city]
  city.blank? || city.match(/^(#{Kitt::Client.query(City::GroupsQuery).data.cities.map { |city| city.slug }.join("|")})$/i)
end

Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  get "/proxy/image", to: 'proxy#image', as: :proxy_image

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  namespace :admin do
    resources :lives, except: [ :index, :destroy ] do
      member do
        patch 'on'
        patch 'off'
      end
    end
    root 'lives#index'
    delete '/log_out', to: 'base#log_out'
  end

  resources :employer_prospects, only: [:create, :index]

  resources :prospects, only: :create

  # config/static_routes.yml
  STATIC_ROUTES.each do |template, locale_paths|
    locale_paths.each do |locale, page|
      get page => "pages##{template}", template: template, locale: locale.to_sym, as: "#{template}_#{locale.to_s.underscore}".to_sym
    end
  end

  # Redirects
  get 'premiere', to: redirect('programme')
  get 'aix-marseille', to: redirect('marseille')
  get 'fr/aix-marseille', to: redirect('fr/marseille')
  get 'sp', to: redirect('pt-BR/sao-paulo')
  get 'bh', to: redirect('pt-BR/belo-horizonte')
  get 'en', to: redirect('/')
  get 'learn(/:city)', to: redirect { |params, _| params[:city].blank? ? 'learn-to-code' : "learn-to-code/#{params[:city]}" }, as: :learn_to_code
  get 'stories', to: redirect('alumni')
  get 'fr/stories', to: redirect('fr/alumni')
  get 'en/*path', to: redirect { |path_params, req| path_params[:path] }

  react_exceptions = ["pt-BR", "zh-CN", "es", "ja"]
  react_exceptions.each do | exception |
    get "#{exception.to_s}/react", to: redirect("/react")
  end


  get 'ondemand/*path', to: redirect { |path_params, req| "https://ondemand.lewagon.com/#{req.fullpath.gsub("/ondemand/", "")}" }
  get 'codingstationparis', to: redirect('https://www.meetup.com/fr-FR/Le-Wagon-Paris-Coding-Station')

  {
    'davidverbustel' => 'david-joins-efounders',
    'oliviergodement' => 'olivier-joined-stripe-as-user-ops-lead',
    'amontcoudiol' => 'adrien-and-max-reinvent-tv',
    'olixier' => 'seeding-one-million-with-kudoz',
    'aliceclv' => 'alice-joins-save-as-backend-dev'
  }.each do |github_nickname, new_slug|
    ['', 'fr/'].each do |locale|
      get "#{locale.to_s.underscore}stories/#{github_nickname}", to: redirect("#{locale.to_s.underscore}stories/#{new_slug}")
    end
  end

  constraints(city_constraint) do
    get "apply/(:city)" => "applies#new", locale: :en, as: :apply_en
    get "postuler/(:city)" => "applies#new", locale: :fr, as: :apply_fr
    get "candidatar/(:city)" => "applies#new", locale: :"pt-BR", as: :apply_pt_br
    get "postularse/(:city)" => "applies#new", locale: :es, as: :apply_es
    get "申请/(:city)" => "applies#new", locale: :"zh-CN", as: :apply_zh_cn
    get "アプライ/(:city)" => "applies#new", locale: :ja, as: :apply_ja
    post "apply/(:city)" => "applies#create", as: :apply
    post "apply/validate" => "applies#validate", as: :validate_apply
  end

  get "blog/rss", to: 'posts#rss', defaults: { format: :xml }, as: :rss

  get "hec", to: 'applies#new_hec', as: :new_hec_apply
  post "hec", to: 'applies#create_hec', as: :hec_apply, locale: :fr

  get "edhec", to: 'applies#new_edhec', as: :new_edhec_apply
  post "edhec", to: 'applies#create_edhec', as: :edhec_apply, locale: :fr

  scope "(:locale)", locale: /fr|pt-BR|zh-CN|es|ja/ do
    root to: "pages#home"
    get "faq", to: "pages#show", template: "faq", as: :faq
    get "jobs", to: "pages#show", template: "jobs", as: :jobs
    get "stack", to: "pages#stack", template: "stack", as: :stack
    get "employers", to: "pages#employers", template: "employers", as: :employers
    get "learn-to-code(/:city)", to: "pages#learn", template: "learn", as: :learn
    get "enterprise", to: "pages#enterprise", template: "enterprise", as: :enterprise
    get "blog/videos", to: "posts#videos", template: "videos", as: :videos
    get "blog/all", to: "posts#all", template: "all", as: :all
    get "alumni" => "students#index", as: :alumni
    get "projects" => "projects#index", as: :projects
    get "blog", to: 'posts#index', as: :blog
    get "blog/:slug", to: 'posts#show', as: :post
    get "live", to: 'pages#live', as: :live
    get "shop" => "pages#shop", as: :shop
    get "vae" => "pages#vae", as: :vae
    get "cgv" => "pages#cgv", as: :cgv
    get "react" => "pages#react", locale: :en, as: :react
    get "lemoisducode" => "pages#lemoisducode", as: :lemoisducode
    get "partners" => "pages#partners", as: :partners

    constraints(city_constraint) do
      get ":city" => "cities#show", as: :city
    end
    resources :projects, only: [:show]
    resources :stories, only: [:show]
    resources :students, only: [:show]
    resources :demoday, only: [:index, :show] do
      member do
        get "*product_slug", to: 'demoday#show', as: :with_slug
      end
    end
  end

  resources :subscribes, only: :create

  # API
  resource :cache, only: :destroy

  # SEO
  get 'robots', to: 'pages#robots'

  # Old
  get 'wagon_bar', to: redirect('/fr')

  # Linkedin Token
  get 'linkedin', to: 'pages#linkedin'

  # Sidekiq
  require "sidekiq/web"
  require "sidekiq/cron/web"
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404" => "application#render_404", via: :all
end

# Create helper for static_routes
Rails.application.routes.url_helpers.module_eval do
  STATIC_ROUTES.each do |route, _|
    define_method "#{route}_path".to_sym do |args = {}|
      locale = args[:locale] || :fr
      self.send(:"#{route}_#{locale.to_s.underscore}_path")
    end

    define_method "#{route}_url".to_sym do |args = {}|
      locale = args[:locale] || :fr
      self.send(:"#{route}_#{locale.to_s.underscore}_url")
    end
  end
end

app/controllers/admin/lives_controller.rb
module Admin
  class LivesController < BaseController
    before_action :set_live, only: [ :on, :off, :edit, :update ]
    before_action :set_city_slugs, only: [ :new, :edit ]

    def index
      @lives = Live.all.order(started_at: :desc, created_at: :desc)
    end

    def new
      if params[:category].blank?
        redirect_to admin_lives_path
      else
        @live = Live.new(category: params[:category])
      end
    end

    def create
      @live = Live.new(live_params)
      @live.user = current_user
      if @live.save
        redirect_to admin_root_path
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @live.update(live_params)
        redirect_to admin_root_path
      else
        render :edit
      end
    end

    def on
      @live.started_at = DateTime.now
      @live.ended_at = nil
      @live.save
      Live.where.not(id: @live.id).where(ended_at: nil).update(ended_at: DateTime.now)
      render :show
    end

    def off
      @live.ended_at = DateTime.now
      @live.save
      render :show
    end

    private

    def live_params
      params.require(:live).permit(:category, :batch_slug, :city_slug, :started_at, :ended_at, :facebook_url, :batch_slug, :title, :subtitle, :description, :link, :meta_image, :company_logo, :interviewee_picture)
    end

    def set_live
      @live = Live.find(params[:id])
    end

    def set_city_slugs
      @city_slugs = Kitt::Client.query(City::GroupsQuery).data.cities.map(&:slug)
    end
  end
end

app/views/admin/lives/_form.html.erb
<%= simple_form_for [:admin, @live] do |f| %>
  <% if @live.demoday? %>
    <%= f.input :batch_slug, placeholder: 43 %>
  <% else %>
    <%= f.input :city_slug, collection: @city_slugs, label: "Where is it happenning?" %>
    <%= f.input :title, placeholder: 'Aperotalk avec Quentin Sannié, Workshop - Build your first website in 2 hour with Boris Paillard' %>
    <%= f.input :subtitle, placeholder: 'CEO & Co-fondateur de DEVIALET', hint: "Goes next to the title at the top of the video" %>
    <%= f.input :description, hint: 'That will go on the right of the video. You can use Markdown in here ☝️' %>
    <%= f.input :link, label: 'Learn more link', placeholder: 'http://www.devialet.fr', hint: "Goes under the description. You can leave this blank if you do not have any link." %>
    <%= f.input :company_logo, as: :attachinary, hint: "Square format (60x60)" %>
    <%= f.input :interviewee_picture, as: :attachinary, hint: "Square format (60x60)" %>
    <%= f.input :meta_image, as: :attachinary, hint: "Super important, will appear as a twitter card when you share the lewagon.com/live URL!" %>
    <%= f.input :facebook_url, label: 'Facebook video url', hint: 'Click on post date and look in the URL', placeholder: 'https://www.facebook.com/lewagon/videos/548038245394778/' %>
  <% end %>
  <%= f.input :category, as: :hidden %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/lives/_live.html.erb
<% if live.demoday? %>
  <td></td>
  <td>
    <strong>Demoday Batch #<%= live.batch_slug %></strong>
    <%= link_to edit_admin_live_path(live) do %>
      <i class="fa fa-pencil"></i> edit
    <% end %>
  </td>
<% else %>
  <td>
    <% if live.meta_image? %>
      <%= cl_image_tag live.meta_image.path, height: 60 %>
    <% end %>
  </td>
  <td style="vertical-align: middle">
    <strong><%= live.title %></strong>
    <% if live.subtitle.present? %>
      - <%= live.subtitle %>
    <% end %>
    <%= link_to edit_admin_live_path(live) do %>
      <i class="fa fa-pencil"></i> edit
    <% end %>
  </td>
<% end %>
<td class="text-right"  style="vertical-align: middle">
  <% if live.started_at.nil? || !live.ended_at.nil? %>
    <%= link_to on_admin_live_path(live), class: 'btn btn-danger', remote: true, method: :patch do %>
      <i class="fa fa-video-camera"></i> Go live!
    <% end %>
  <% elsif live.ended_at.nil? %>
    Started at <%= l live.started_at, format: :short %>
    <%= link_to off_admin_live_path(live), class: 'btn btn-warning', remote: true, method: :patch do %>
      <i class="fa fa-stop"></i> End live
    <% end %>
  <% end %>
</td>

app/views/admin/lives/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Edit live event</h1>

    <%= render 'form', live: @live %>
  </div>
</div>

app/views/admin/lives/index.html.erb
<%= link_to "New Event", new_admin_live_path(category: 'aperotalk'), class: 'btn btn-primary pull-right', style: 'margin-left: 1em' %>
<%= link_to "New Demoday", new_admin_live_path(category: 'demoday'), class: 'btn btn-default pull-right' %>

<div class="clearfix" style="height: 5em"></div>

<table class="table table-striped">
  <% @lives.each do |live| %>
    <tr data-live-id="<%= live.id %>">
      <%= render 'live', live: live %>
    </tr>
  <% end %>
</table>

app/views/admin/lives/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>New live</h1>
    <%= render 'form', live: @live %>
  </div>
</div>

app/views/admin/lives/show.js.erb
$('[data-live-id=<%= @live.id %>]').html('<%= j render "live", live: @live %>');