config/routes.rb
city_constraint = Proc.new do |req|
  city = req.params[:city]
  city.blank? || city.match(/^(#{Kitt::Client.query(City::GroupsQuery).data.cities.map { |city| city.slug }.join("|")})$/i)
end

Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  get "/proxy/image", to: 'proxy#image', as: :proxy_image

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  namespace :admin do
    resources :lives, except: [ :index, :destroy ] do
      member do
        patch 'on'
        patch 'off'
      end
    end
    root 'lives#index'
    delete '/log_out', to: 'base#log_out'
  end

  resources :employer_prospects, only: [:create, :index]

  resources :prospects, only: :create

  # config/static_routes.yml
  STATIC_ROUTES.each do |template, locale_paths|
    locale_paths.each do |locale, page|
      get page => "pages##{template}", template: template, locale: locale.to_sym, as: "#{template}_#{locale.to_s.underscore}".to_sym
    end
  end

  # Redirects
  get 'premiere', to: redirect('programme')
  get 'aix-marseille', to: redirect('marseille')
  get 'fr/aix-marseille', to: redirect('fr/marseille')
  get 'sp', to: redirect('pt-BR/sao-paulo')
  get 'bh', to: redirect('pt-BR/belo-horizonte')
  get 'en', to: redirect('/')
  get 'learn(/:city)', to: redirect { |params, _| params[:city].blank? ? 'learn-to-code' : "learn-to-code/#{params[:city]}" }, as: :learn_to_code
  get 'stories', to: redirect('alumni')
  get 'fr/stories', to: redirect('fr/alumni')
  get 'en/*path', to: redirect { |path_params, req| path_params[:path] }

  react_exceptions = ["pt-BR", "zh-CN", "es", "ja"]
  react_exceptions.each do | exception |
    get "#{exception.to_s}/react", to: redirect("/react")
  end


  get 'ondemand/*path', to: redirect { |path_params, req| "https://ondemand.lewagon.com/#{req.fullpath.gsub("/ondemand/", "")}" }
  get 'codingstationparis', to: redirect('https://www.meetup.com/fr-FR/Le-Wagon-Paris-Coding-Station')

  {
    'davidverbustel' => 'david-joins-efounders',
    'oliviergodement' => 'olivier-joined-stripe-as-user-ops-lead',
    'amontcoudiol' => 'adrien-and-max-reinvent-tv',
    'olixier' => 'seeding-one-million-with-kudoz',
    'aliceclv' => 'alice-joins-save-as-backend-dev'
  }.each do |github_nickname, new_slug|
    ['', 'fr/'].each do |locale|
      get "#{locale.to_s.underscore}stories/#{github_nickname}", to: redirect("#{locale.to_s.underscore}stories/#{new_slug}")
    end
  end

  constraints(city_constraint) do
    get "apply/(:city)" => "applies#new", locale: :en, as: :apply_en
    get "postuler/(:city)" => "applies#new", locale: :fr, as: :apply_fr
    get "candidatar/(:city)" => "applies#new", locale: :"pt-BR", as: :apply_pt_br
    get "postularse/(:city)" => "applies#new", locale: :es, as: :apply_es
    get "申请/(:city)" => "applies#new", locale: :"zh-CN", as: :apply_zh_cn
    get "アプライ/(:city)" => "applies#new", locale: :ja, as: :apply_ja
    post "apply/(:city)" => "applies#create", as: :apply
    post "apply/validate" => "applies#validate", as: :validate_apply
  end

  get "blog/rss", to: 'posts#rss', defaults: { format: :xml }, as: :rss

  get "hec", to: 'applies#new_hec', as: :new_hec_apply
  post "hec", to: 'applies#create_hec', as: :hec_apply, locale: :fr

  get "edhec", to: 'applies#new_edhec', as: :new_edhec_apply
  post "edhec", to: 'applies#create_edhec', as: :edhec_apply, locale: :fr

  scope "(:locale)", locale: /fr|pt-BR|zh-CN|es|ja/ do
    root to: "pages#home"
    get "faq", to: "pages#show", template: "faq", as: :faq
    get "jobs", to: "pages#show", template: "jobs", as: :jobs
    get "stack", to: "pages#stack", template: "stack", as: :stack
    get "employers", to: "pages#employers", template: "employers", as: :employers
    get "learn-to-code(/:city)", to: "pages#learn", template: "learn", as: :learn
    get "enterprise", to: "pages#enterprise", template: "enterprise", as: :enterprise
    get "blog/videos", to: "posts#videos", template: "videos", as: :videos
    get "blog/all", to: "posts#all", template: "all", as: :all
    get "alumni" => "students#index", as: :alumni
    get "projects" => "projects#index", as: :projects
    get "blog", to: 'posts#index', as: :blog
    get "blog/:slug", to: 'posts#show', as: :post
    get "live", to: 'pages#live', as: :live
    get "shop" => "pages#shop", as: :shop
    get "vae" => "pages#vae", as: :vae
    get "cgv" => "pages#cgv", as: :cgv
    get "react" => "pages#react", locale: :en, as: :react
    get "lemoisducode" => "pages#lemoisducode", as: :lemoisducode
    get "partners" => "pages#partners", as: :partners

    constraints(city_constraint) do
      get ":city" => "cities#show", as: :city
    end
    resources :projects, only: [:show]
    resources :stories, only: [:show]
    resources :students, only: [:show]
    resources :demoday, only: [:index, :show] do
      member do
        get "*product_slug", to: 'demoday#show', as: :with_slug
      end
    end
  end

  resources :subscribes, only: :create

  # API
  resource :cache, only: :destroy

  # SEO
  get 'robots', to: 'pages#robots'

  # Old
  get 'wagon_bar', to: redirect('/fr')

  # Linkedin Token
  get 'linkedin', to: 'pages#linkedin'

  # Sidekiq
  require "sidekiq/web"
  require "sidekiq/cron/web"
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404" => "application#render_404", via: :all
end

# Create helper for static_routes
Rails.application.routes.url_helpers.module_eval do
  STATIC_ROUTES.each do |route, _|
    define_method "#{route}_path".to_sym do |args = {}|
      locale = args[:locale] || :fr
      self.send(:"#{route}_#{locale.to_s.underscore}_path")
    end

    define_method "#{route}_url".to_sym do |args = {}|
      locale = args[:locale] || :fr
      self.send(:"#{route}_#{locale.to_s.underscore}_url")
    end
  end
end

app/views/shared/_facebook_audience.html.erb
<%
  general_audience_tracker = '751967801553090'
%>

<% unless (@city && @city.apply_facebook_pixel == general_audience_tracker) %>
<script class="_iub_cs_activate-inline" type="text/plain">(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
  _fbq.push(['addPixelId', '<%= general_audience_tracker %>']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<% end %>

app/views/shared/_features.html.erb
<% cache [ 'features', locale, wrapper_up ] do %>
<div class="features-wrapper <%= wrapper_up ? 'up' : nil %>">
  <div class="container features-container">
    <h2 class='section-title-home'>
      <div class='section-title-home-content' style="font-size:30px;">
        <%= t(".pedagogy_matters_html") %>
      </div>
    </h2>
    <div class='features'>
      <div class='feature'>
        <div class='feature-header'>
          <div class='feature-icon yellow'>
            <i class='mdi mdi-laptop'></i>
          </div>
          <h2 class='feature-title'>
            <%= t(".web_development") %>
          </h2>
        </div>
        <div class='feature-body'>
          <%= t(".web_development_details") %><%= link_to t(".see_all"), send(:"program_#{locale.to_s.underscore}_path") %>
        </div>
      </div>
      <div class='feature'>
        <div class='feature-header'>
          <div class='feature-icon purple'>
            <i class='mdi mdi-keyboard-variant'></i>
          </div>
          <h2 class='feature-title'>
            <%= t(".software_engineer_html") %>
          </h2>
        </div>
        <div class='feature-body'>
          <%= t(".software_engineer_details") %>
        </div>
      </div>
      <div class='feature'>
        <div class='feature-header'>
          <div class='feature-icon green'>
          <i class='mdi mdi-source-pull'></i>
          </div>
          <h2 class='feature-title'>
            <%= t(".technical_workflow") %>
          </h2>
        </div>
        <div class='feature-body'>
          <%= t(".technical_workflow_details_html") %>
        </div>
      </div>
       <div class='feature'>
        <div class='feature-header'>
          <div class='feature-icon orange'>
            <i class='mdi mdi-auto-fix'></i>
          </div>
          <h2 class='feature-title'>
            <%= t(".startup_toolkit") %>
          </h2>
        </div>
        <div class='feature-body'>
          <%= t(".startup_toolkit_details") %>
        </div>
      </div>
      <div class='feature'>
        <div class='feature-header'>
          <div class='feature-icon blue'>
            <i class='mdi mdi-cube-outline'></i>
          </div>
          <h2 class='feature-title'>
            <%= t(".build_product") %>
          </h2>
        </div>
        <div class='feature-body'>
          <%= t(".build_product_details") %><%= link_to t(".checkout"), alumni_path %>
        </div>
      </div>
      <div class='feature'>
        <div class='feature-header'>
          <div class='feature-icon red'>
            <i class='mdi mdi-wallet-travel'></i>
          </div>
          <h2 class='feature-title'>
            <%= t(".land_a_job") %>
          </h2>
        </div>
        <div class='feature-body'>
          <%= t(".land_a_job_details") %>
        </div>
      </div>
    </div>
    <div class="text-center" style="margin-top: 50px;">
      <%= link_to t(".read_full_program"), send(:"program_#{locale.to_s.underscore}_path"), class: 'link-big' %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_iubenda.html.erb
<script async type="text/javascript">
  var _iub = _iub || [];
  _iub.csConfiguration = {
    cookiePolicyId: 7967062,
    siteId: 662533,
    lang: "<%= I18n.locale %>"
  };
</script>
<script async type="text/javascript" src="//cdn.iubenda.com/cookie_solution/safemode/iubenda_cs.js" charset="UTF-8" async></script>

app/views/shared/_more_testimonials.html.erb
<% if @testimonials %>
  <% @testimonials.each_slice(2) do |testimonials| %>
    <div class="row">
      <% testimonials.each do |testimonial| %>
        <% cache [ 'testimonial', testimonial, I18n.locale ] do %>
        <!-- EXCERPT CONTENT -->
        <div class="col-md-6">
          <%= link_to '', '#', class: 'read-more', "data-toggle" => "modal", 'data-target' => "#fullTestimonial-#{testimonial.github_nickname}" %>
          <div class="testimonial-card">
            <div class="testimonial-body">
              <%= image_tag testimonial.picture_url(109, 109, 90), alt: testimonial.name, class: 'alumni-picture' %>
              <div class='testimonial-content'>
                <%= raw testimonial.content_html.truncate(120) %>
                <i class="read-more-text"><%= t('.read_more') %></i>
              </div>
              <div class="testimonial-author">
                <div class="testimonial-user-name">
                  <%= testimonial.first_name %>  <%= testimonial.last_name %>
                </div>
                <div class='testimonial-user-batch'>
                  Batch #<%= testimonial.batch_slug %>, <%= testimonial.city.name %>
                </div>
                <div class='testimonial-user-batch'>
                  <%= t('.published_on') %> <%= testimonial.origin %>, <%= testimonial.publication_date.strftime('%d %b %Y') %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- MODAL CONTENT -->
        <div class="modal fade" id="fullTestimonial-<%= testimonial.github_nickname %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
          <div class="modal-dialog modal-testimonial" role="document">
            <div class="modal-content">
              <div class="modal-header" style="background-image: url(<%= cl_image_path testimonial.city.city_background_picture, width: 938, height: 266, crop: :fill if testimonial.city.city_background_picture %>)">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
              <div class="modal-body">
                <div class="row">
                  <div class="col-md-10 col-md-offset-1">
                    <div class="alumni-profil">
                      <%= image_tag testimonial.picture_url(109, 109, 90), alt: testimonial.name, class: 'alumni-picture' %>
                      <div class="alumni-details">
                        <h4 class="modal-title">
                          <%= testimonial.name %>
                          <% if testimonial.linkedin_url.present? %>
                            <%= link_to testimonial.linkedin_url, target: :_blank, class: 'linkedin' do %>
                              <%= render 'shared/linkedin' %>
                            <% end %>
                          <% end %>
                        </h4>
                        <span>Batch #<%= testimonial.batch_slug %> - <%= testimonial.city.name %></span>
                      </div>
                    </div>
                  </div>
                  <% if testimonial.job_before.present? && testimonial.job_after.present? && testimonial.new_company.present? %>
                    <div class="col-xs-10 col-xs-offset-1 alumni-timeline">
                      <div class="row">
                        <div class="col-xs-4 now marker-before <%= I18n.locale.to_s.underscore %>">
                          <i class="alumni-job-position"><%= testimonial.job_before %></i>
                        </div>
                        <div class="col-xs-4 lewagon">
                          <%= render "shared/logos/logo_circle_red" %>
                        </div>
                        <div class="col-xs-4  after marker-after <%= I18n.locale.to_s.underscore %>">
                          <i class="alumni-job-position"><%= testimonial.job_after %><br>at <%= testimonial.new_company %></i>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  <div class="col-xs-10 col-xs-offset-1 alumni-content">
                    <i><%= t('.published_on') %> <%= testimonial.origin %>, <%= testimonial.publication_date.strftime('%d %b %Y') %></i>
                    <%= raw testimonial.content_html %>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <% if testimonial.product.present? %>
                  <div class="alumni-product-container">
                    <h4><%= t('.watch', name: testimonial.first_name) %></h4>
                    <a href=" <%= demoday_path testimonial.batch_slug %>/<%= testimonial.product.slug %>">
                      <% if testimonial&.product&.cover_picture_url %>
                        <div class="video-thumbnail" style="background-image: url(<%= thumbnail_url(testimonial.product) %>);">
                      <% elsif testimonial&.batch&.meta_image_url %>
                        <div class="video-thumbnail" style="background-image: url(<%= cl_image_path testimonial.batch.meta_image_url %>);">
                      <% else %>
                        <div class="video-thumbnail" style="background-image: url(<%= cl_image_path testimonial.city.city_background_picture, height: 200, crop: :fill %>);">
                      <% end %>
                        <svg id="play-button" width="33px" height="33px" viewBox="0 0 33 33" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                          <g id="play" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <path d="M16.5,32 C25.0604136,32 32,25.0604136 32,16.5 C32,7.93958638 25.0604136,1 16.5,1 C7.93958638,1 1,7.93958638 1,16.5 C1,25.0604136 7.93958638,32 16.5,32 Z M22.7543284,16.4569667 L12,22.4003482 L12,11 L22.7543284,16.4569667 Z" id="Oval" stroke="#ffffff"></path>
                          </g>
                        </svg>
                      </div>
                      <div class="video-details">
                        <h4 class="text-center"><%= testimonial.product.name %><small><%= testimonial.product.tagline %></small></h4>
                      </div>
                    </a>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<% cache ['navbar',
    Digest::SHA1.hexdigest(@top_bar_message || ""),
    Digest::SHA1.hexdigest(@top_bar_cta || ""),
    @hide_language_selector,
    @city_groups,
    params[:controller],
    params[:action],
    params[:city],
    Static::ONDEMAND_TRACKS.map { |track| track[:slug] },
    I18n.locale ] do %>

<% if @top_bar_message.present? && @top_bar_cta.present? %>
  <div id="sticky-banner">
    <i><%= @top_bar_message %>, <%= link_to @top_bar_cta, @top_bar_url %></i>
  </div>
<% end %>

<nav class="navbar-wagon navbar-wagon-white <% if @top_bar_message.present? %>navbar-jump<% end %>">
  <div class="container navbar-wagon-container">
    <div class='navbar-wagon-side'>
      <%= render 'shared/navbar_dropdown', full_item: false %>
      <% unless @hide_language_selector %>
        <div class="hidden-xs hidden-sm">
          <%= render 'shared/language_selector' %>
        </div>
      <% end %>

      <div class="left hidden-sm hidden-xs">
        <div class="navbar-wagon-item has-no-padding">
          <div class="dropdown">
            <%= link_to t(".menu.cities"),"#", class: "hidden-xs  dropdown-toggle navbar-wagon-link ", id: "navbar-wagon-menu", data: { toggle: 'dropdown'} %>
            <div class="dropdown-menu dropdown-menu-right dropdown-cities">
              <div class="dropdown-cities-container">
                <% @city_groups.each do |city_group| %>
                  <ul class="list-unstyled">
                    <li class="title">
                      <%= city_group[:group].html_safe %>
                      <%= city_group[:flag_svg].html_safe %>
                    </li>
                    <% city_group[:cities].each do |city| %>
                      <li>
                        <%= link_to city.name, city_path(city: city.slug), style: "font-weight: 200; color: black" %>
                      </li>
                    <% end %>
                  </ul>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <hr class='hidden-xs'>


      <% if I18n.locale == :fr %>
        <div class="navbar-wagon-item has-no-padding">
          <div class="dropdown">
            <%= link_to t(".menu.program"),"#", class: "hidden-xs  dropdown-toggle navbar-wagon-link ", id: "navbar-wagon-menu", data: { toggle: 'dropdown'} %>
            <div class="dropdown-menu dropdown-menu-right dropdown-cities">
              <div class="dropdown-cities-container <%= 'text-center' unless I18n.locale == :fr %>">
                  <ul class="list-unstyled">
                    <li class="title">
                      <%= t ".menu.on_site", default: "Onsite" %>
                    </li>
                    <li>
                      <%= link_to t(".menu.fullstack_program"), send(:"program_#{locale.to_s.underscore}_path"), class: "cta-enterprise red", style: "min-width: 304px;"%>
                    </li>
                    <!--
                    <% if I18n.locale == :fr %>
                      <li>
                        <%= link_to t(".menu.react_program"), react_path(locale: :fr), class: "cta-enterprise", style: "min-width: 304px;" %>
                      </li>
                    <% elsif I18n.locale == :en %>
                      <li>
                        <%= link_to t(".menu.react_program"), react_path, class: "cta-enterprise", style: "min-width: 323px;" %>
                      </li>
                    <% end %>
                    -->
                    <% unless I18n.locale == :fr %>
                      </ul>
                      <ul class="list-unstyled">
                    <% end %>
                  </ul>

                  <% if I18n.locale == :fr %>
                    <ul class="list-unstyled">
                      <li class="title">
                        <%= t ".menu.ondemand", default: "On-Demand" %>
                      </li>
                        <% Static::ONDEMAND_TRACKS.each do |track| %>
                          <li style="padding: 3px 0px;text-align: left;">
                            <a href="https://ondemand.lewagon.com/tracks/<%= track[:slug] %>/go?utm_medium=referral&utm_source=www.lewagon.com&utm_campaign=navbar_wagon" target='_blank' style="font-size: 15px; font-weight: 100;">
                              <%= track[:title] %>
                              <% if track[:new] %>
                              <span class="new">new</span>
                              <% end %>
                           </a>
                          </li>
                        <% end %>
                        <li style="padding: 3px 0px;text-align: left;">
                          <a href="https://ondemand.lewagon.com/gift?utm_medium=referral&utm_source=www.lewagon.com&utm_campaign=navbar_wagon" target="_blank" style="font-size: 15px; font-weight: 100;">
                            <i class="fa fa-gift"></i> <em>Offrez une track</em>
                          </a>
                        </li>
                    </ul>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <%= link_to t(".menu.program"), send(:"program_#{I18n.locale.to_s.underscore}_path"), class: "hidden-xs navbar-wagon-link " %>
      <% end %>
        <hr class="hidden-xs">
        <%= link_to "FAQ", faq_path, class: 'navbar-wagon-link' %>
        <hr class="hidden-xs">
        <%= link_to "Blog", blog_path, class: 'navbar-wagon-link' %>
        <hr class='fake-hr hidden-sm hidden-xs'>
      </div>
      </div>
      <%= link_to root_path, class: 'wagon-link hidden-sm hidden-md hidden-lg' do %>
        <%= render "shared/logos/logo_red" %>
      <% end %>
      <%= link_to root_path, class: 'wagon-link hidden-xs' do %>
        <%= render "shared/logos/logo_red_square" %>
      <% end %>
      <% if params[:action] == 'new_hec' %>
        <div class="navbar-hec-logo">
          <%= render "shared/logos/hec" %>
        </div>
      <% elsif params[:action] == 'new_edhec' %>
        <div class="navbar-hec-logo">
          <%= render "shared/logos/edhec" %>
        </div>

      <% elsif @live %>
        <%= link_to live_path, class: 'live-on' do %>
          <i class="dot fa fa-circle fa-pulse"></i> LIVE
        <% end %>
      <% end %>

      <div class="navbar-wagon-side text-right hidden-sm hidden-xs">
        <hr class='fake-hr hidden-xs'>
        <%= link_to "Demoday", demoday_index_path, class: "navbar-wagon-link" %>
        <hr class="hidden-xs">
        <%= link_to t(".alumni", default: "Alumni"), alumni_path, class: " hidden-xs navbar-wagon-link", data: {text: t(".alumni", default: "Alumni")} %>
        <hr class='hidden-xs'>
        <div class="navbar-wagon-item has-no-padding">
          <div class="dropdown">
            <%= link_to t(".employers"),"#", class: "hidden-xs  dropdown-toggle navbar-wagon-link ", id: "navbar-wagon-menu", data: { toggle: 'dropdown'} %>
            <div class="dropdown-menu dropdown-menu-right dropdown-cities">
              <div class="dropdown-cities-container">
                  <ul class="list-unstyled">
                    <li class="title text-center" style="font-weight: 100;margin-top: 10px;">
                      <%= t(".recruitment", default: "Recruitment") %> 🌟
                    </li>
                    <li class="text-center">
                      <%= link_to employers_path, class: "cta-enterprise" do %>
                        <%= t(".work", default: "Work with our alumni") %>
                      <% end %>
                    </li>
                  </ul>
                  <ul class="list-unstyled">
                    <li class="title text-center" style="font-weight: 100;margin-top: 10px;">
                      <%= t(".workshops", default: "Corporate Workshop") %> 🚀
                    </li>
                    <li class="text-center">
                      <%= link_to enterprise_path, class: "cta-enterprise" do %>
                        <%= t(".train", default: "Train your company") %>
                      <% end %>
                    </li>
                  </ul>
              </div>
            </div>
          </div>
        </div>

        <% unless @hide_banner_apply_button %>
          <div class="left" id="navbar-apply">
            <%= content_for?(:navbar_apply_button) ? yield(:navbar_apply_button) : render('shared/navbar_apply_button') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<div class="header-fixed">
  <div class="header-inner">
    <div class="container flex align-center">
      <%= render 'shared/navbar_dropdown', full_item: true %>
      <div class='header-fixed-logo'>
        <a class='wagon-link' href="/">
          <%= render "shared/logos/logo_red_square" %>
        </a>
      </div>
      <div class="header-inner-cta">
        <%= link_to t(".apply"), send(:"apply_#{locale.to_s.underscore}_path"), class: 'navbar-wagon-link-cta' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_navbar_apply_button.html.erb
<% if defined?(city) %>
  <% path = send(:"apply_#{locale.to_s.underscore}_path", city: city) %>
<% else %>
  <% path = send(:"apply_#{locale.to_s.underscore}_path") %>
<% end %>
<%= link_to t("shared.navbar.apply"), path, class: 'navbar-wagon-link-cta' %>