config/routes.rb
city_constraint = Proc.new do |req|
  city = req.params[:city]
  city.blank? || city.match(/^(#{Kitt::Client.query(City::GroupsQuery).data.cities.map { |city| city.slug }.join("|")})$/i)
end

Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  get "/proxy/image", to: 'proxy#image', as: :proxy_image

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  namespace :admin do
    resources :lives, except: [ :index, :destroy ] do
      member do
        patch 'on'
        patch 'off'
      end
    end
    root 'lives#index'
    delete '/log_out', to: 'base#log_out'
  end

  resources :employer_prospects, only: [:create, :index]

  resources :prospects, only: :create

  # config/static_routes.yml
  STATIC_ROUTES.each do |template, locale_paths|
    locale_paths.each do |locale, page|
      get page => "pages##{template}", template: template, locale: locale.to_sym, as: "#{template}_#{locale.to_s.underscore}".to_sym
    end
  end

  # Redirects
  get 'premiere', to: redirect('programme')
  get 'aix-marseille', to: redirect('marseille')
  get 'fr/aix-marseille', to: redirect('fr/marseille')
  get 'sp', to: redirect('pt-BR/sao-paulo')
  get 'bh', to: redirect('pt-BR/belo-horizonte')
  get 'en', to: redirect('/')
  get 'learn(/:city)', to: redirect { |params, _| params[:city].blank? ? 'learn-to-code' : "learn-to-code/#{params[:city]}" }, as: :learn_to_code
  get 'stories', to: redirect('alumni')
  get 'fr/stories', to: redirect('fr/alumni')
  get 'en/*path', to: redirect { |path_params, req| path_params[:path] }

  react_exceptions = ["pt-BR", "zh-CN", "es", "ja"]
  react_exceptions.each do | exception |
    get "#{exception.to_s}/react", to: redirect("/react")
  end


  get 'ondemand/*path', to: redirect { |path_params, req| "https://ondemand.lewagon.com/#{req.fullpath.gsub("/ondemand/", "")}" }
  get 'codingstationparis', to: redirect('https://www.meetup.com/fr-FR/Le-Wagon-Paris-Coding-Station')

  {
    'davidverbustel' => 'david-joins-efounders',
    'oliviergodement' => 'olivier-joined-stripe-as-user-ops-lead',
    'amontcoudiol' => 'adrien-and-max-reinvent-tv',
    'olixier' => 'seeding-one-million-with-kudoz',
    'aliceclv' => 'alice-joins-save-as-backend-dev'
  }.each do |github_nickname, new_slug|
    ['', 'fr/'].each do |locale|
      get "#{locale.to_s.underscore}stories/#{github_nickname}", to: redirect("#{locale.to_s.underscore}stories/#{new_slug}")
    end
  end

  constraints(city_constraint) do
    get "apply/(:city)" => "applies#new", locale: :en, as: :apply_en
    get "postuler/(:city)" => "applies#new", locale: :fr, as: :apply_fr
    get "candidatar/(:city)" => "applies#new", locale: :"pt-BR", as: :apply_pt_br
    get "postularse/(:city)" => "applies#new", locale: :es, as: :apply_es
    get "申请/(:city)" => "applies#new", locale: :"zh-CN", as: :apply_zh_cn
    get "アプライ/(:city)" => "applies#new", locale: :ja, as: :apply_ja
    post "apply/(:city)" => "applies#create", as: :apply
    post "apply/validate" => "applies#validate", as: :validate_apply
  end

  get "blog/rss", to: 'posts#rss', defaults: { format: :xml }, as: :rss

  get "hec", to: 'applies#new_hec', as: :new_hec_apply
  post "hec", to: 'applies#create_hec', as: :hec_apply, locale: :fr

  get "edhec", to: 'applies#new_edhec', as: :new_edhec_apply
  post "edhec", to: 'applies#create_edhec', as: :edhec_apply, locale: :fr

  scope "(:locale)", locale: /fr|pt-BR|zh-CN|es|ja/ do
    root to: "pages#home"
    get "faq", to: "pages#show", template: "faq", as: :faq
    get "jobs", to: "pages#show", template: "jobs", as: :jobs
    get "stack", to: "pages#stack", template: "stack", as: :stack
    get "employers", to: "pages#employers", template: "employers", as: :employers
    get "learn-to-code(/:city)", to: "pages#learn", template: "learn", as: :learn
    get "enterprise", to: "pages#enterprise", template: "enterprise", as: :enterprise
    get "blog/videos", to: "posts#videos", template: "videos", as: :videos
    get "blog/all", to: "posts#all", template: "all", as: :all
    get "alumni" => "students#index", as: :alumni
    get "projects" => "projects#index", as: :projects
    get "blog", to: 'posts#index', as: :blog
    get "blog/:slug", to: 'posts#show', as: :post
    get "live", to: 'pages#live', as: :live
    get "shop" => "pages#shop", as: :shop
    get "vae" => "pages#vae", as: :vae
    get "cgv" => "pages#cgv", as: :cgv
    get "react" => "pages#react", locale: :en, as: :react
    get "lemoisducode" => "pages#lemoisducode", as: :lemoisducode
    get "partners" => "pages#partners", as: :partners

    constraints(city_constraint) do
      get ":city" => "cities#show", as: :city
    end
    resources :projects, only: [:show]
    resources :stories, only: [:show]
    resources :students, only: [:show]
    resources :demoday, only: [:index, :show] do
      member do
        get "*product_slug", to: 'demoday#show', as: :with_slug
      end
    end
  end

  resources :subscribes, only: :create

  # API
  resource :cache, only: :destroy

  # SEO
  get 'robots', to: 'pages#robots'

  # Old
  get 'wagon_bar', to: redirect('/fr')

  # Linkedin Token
  get 'linkedin', to: 'pages#linkedin'

  # Sidekiq
  require "sidekiq/web"
  require "sidekiq/cron/web"
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404" => "application#render_404", via: :all
end

# Create helper for static_routes
Rails.application.routes.url_helpers.module_eval do
  STATIC_ROUTES.each do |route, _|
    define_method "#{route}_path".to_sym do |args = {}|
      locale = args[:locale] || :fr
      self.send(:"#{route}_#{locale.to_s.underscore}_path")
    end

    define_method "#{route}_url".to_sym do |args = {}|
      locale = args[:locale] || :fr
      self.send(:"#{route}_#{locale.to_s.underscore}_url")
    end
  end
end

app/models/story.rb
class Story
  include MarkdownArticle

  def post?
    true
  end

  def story?
    true
  end

  def video?
    false
  end

  def slug
    @slug ||= (Pathname.new(@file).basename.to_s[/(.*)\.md/, 1])
  end

  def date
    @date ||= Date.parse(metadata[:date])
  end

  def company
    @company ||= (Company.find(metadata[:company_slug]) || Company.find('lewagon'))
  end

  def locale
    metadata[:locale]
  end

  def alumnus
    @alumnus ||= Kitt::Client.query(
      Student::UserQuery,
      variables: { github_nickname: metadata[:alumnus_github_nickname] }
    ).data.user
  end

  def city
    return nil if city_slug.blank?
    @city ||= Kitt::Client.query(City::Query, variables: { slug: city_slug }).data.city
  end

  def labels
    %w(alumni story)
  end

  def author
    {
      fname: alumnus.first_name,
      lname: alumnus.last_name,
      picture: alumnus.official_avatar_url,
      batch: alumnus.camp.slug,
      city: alumnus.camp.city.name
    }
  end

  def as_json(options = {})
    {
      slug: slug,
      thumbnail: thumbnail,
      title: title,
      description: description,
      company: {
        url: company.url,
        logo: company.logo
      },
      alumnus: {
        first_name: alumnus.first_name,
        official_avatar_url: alumnus.official_avatar_url,
        camp: {
          slug: alumnus.camp.slug
        },
        city: {
          name: alumnus.camp.city.name
        }
      }
    }
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def show
    @story = Story.find(params[:id])
    return render_404 if @story.blank?

    session[:story_slug] = [] if session[:story_slug].nil?
    session[:story_slug] << @story.slug
    session[:story_slug].uniq!

    @stories = Story.random(limit: 2, excluded_slugs: session[:story_slugs])
  end
end

app/views/stories/_social_sharing.html.erb
<ul class="social-sharing">
  <li><%= ('share') %></li>
  <li>
    <a href="http://twitter.com/home?status=<%= raw @story.title %>+<%= request.url %>" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=240,width=600');return false;">
        <i class="fa fa-twitter" aria-hidden="true"></i>
    </a>
  </li>
  <li>
    <i id="shareBtn" class="fa fa-facebook" aria-hidden="true"></i>
  </li>
  <li>
    <a href="http://www.linkedin.com/shareArticle?mini=true&url=<%=request.url %>&title=<%= raw @story.title %>&source=lewagon.com" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=240,width=600');return false;">
      <i class="fa fa-linkedin" aria-hidden="true"></i>
    </a>
    </li>
</ul>

app/views/stories/_user_infos.html.erb
<div class="story-banner-user">
  <% if story.alumnus %>
    <div class="story-user-avatar">
      <%= link_to alumnus_profile_path(story.alumnus), target: :_blank do %>
        <%= cl_adaptive_image_tag story.alumnus.official_avatar_url, width: 45, height: 45, crop: :fill %>
      <% end %>
    </div>
    <div class="story-banner-infos">
      <div class="story-user-name">
        <span>Featuring</span>
        <%= link_to story.alumnus.name, alumnus_profile_path(story.alumnus), target: :_blank %>
      </div>
      <div class="story-user-batch">
        Le Wagon, Batch #<%= story.alumnus.camp.slug %>, <%= story.alumnus.camp.city.name %>
      </div>
    </div>
  <% end %>
  <img class="story-company-logo" src="<%= story.company.logo %>" />
</div>

app/views/stories/show.html.erb
<%= content_for(:title) { t(".title", story: @story.title).html_safe } %>
<%= content_for(:description) { t(".description", story: @story.description) } %>
<%= content_for(:image_url) { story_image_url(@story.thumbnail) if @story.thumbnail } %>

<!-- FACEBOOK SDK ON SHOW VIEW -->
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '737501859652485',
      xfbml      : true,
      version    : 'v2.9'
    });

    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<div class="story-banner banner banner-top">
  <div class="filter" class="perpetua filter"
       style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= story_image_url @story.thumbnail, width: 1400 %>');"></div>
  <div class="story-banner-content story-container">
    <h2><%= @story.title %></h2>
    <%= render 'user_infos', story: @story %>
  </div>
</div>

<div class='container story-wrapper'>
  <div class="row">

    <!-- AFFIX - SOCIAL SHARING OPTIONS -->
    <div class="col-md-2">
      <div data-spy="affix" data-offset-top="630" data-offset-bottom="2300">
        <%= render 'stories/social_sharing' %>
      </div>
    </div>

    <div class="col-md-8 story-body">
      <div class="story-company">
        <% if @story.company %>
          <img src="<%= @story.company.logo %>" class="story-company-logo">
        <% end %>
      </div>
      <div class="story-summary">
        <%= markdown(@story.description) %>
      </div>
      <div class="story-description">
        <%= markdown(@story.content) %>
        <h3 class="last"><%= t(".continue") %></h3>
        <p><%= t(".read_more") %></p>
      </div>
    </div>
  </div>
</div>

<div class="stories-container">
  <div class="story-container popular-stories">
    <%= t(".other_testimonials") %>
  </div>
  <% @stories.each do |story| %>
    <div class="story-container">
      <div class="story-card">
        <main>
          <div class="story-card-title">
            <%= story.title %>
          </div>
          <div class="story-card-summary">
            <%= story.description %>
          </div>
          <div class='story-card-footer'>
            <%= render 'user_infos', story: story %>
          </div>
        </main>
        <aside>
          <div class="background perpetua" id="<%= story.alumnus.github_nickname %>" style="background-image: url('<%= story_image_url story.thumbnail, width: 240 %>')">
          </div>
        </aside>
        <%= link_to "", story_path(id: story.slug), class: "story-card-link" %>
      </div>
    </div>
  <% end %>
</div>

<% content_for(:after_js) do %>
  <script>
    document.getElementById('shareBtn').onclick = function() {
      FB.ui({
        method: 'share',
        display: 'popup',
        href: window.location.href,
      }, function(response){});
    }
  </script>
<% end %>