config/routes.rb
city_constraint = Proc.new do |req|
  city = req.params[:city]
  city.blank? || city.match(/^(#{Kitt::Client.query(City::GroupsQuery).data.cities.map { |city| city.slug }.join("|")})$/i)
end

Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  get "/proxy/image", to: 'proxy#image', as: :proxy_image

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  namespace :admin do
    resources :lives, except: [ :index, :destroy ] do
      member do
        patch 'on'
        patch 'off'
      end
    end
    root 'lives#index'
    delete '/log_out', to: 'base#log_out'
  end

  resources :employer_prospects, only: [:create, :index]

  resources :prospects, only: :create

  # config/static_routes.yml
  STATIC_ROUTES.each do |template, locale_paths|
    locale_paths.each do |locale, page|
      get page => "pages##{template}", template: template, locale: locale.to_sym, as: "#{template}_#{locale.to_s.underscore}".to_sym
    end
  end

  # Redirects
  get 'premiere', to: redirect('programme')
  get 'aix-marseille', to: redirect('marseille')
  get 'fr/aix-marseille', to: redirect('fr/marseille')
  get 'sp', to: redirect('pt-BR/sao-paulo')
  get 'bh', to: redirect('pt-BR/belo-horizonte')
  get 'en', to: redirect('/')
  get 'learn(/:city)', to: redirect { |params, _| params[:city].blank? ? 'learn-to-code' : "learn-to-code/#{params[:city]}" }, as: :learn_to_code
  get 'stories', to: redirect('alumni')
  get 'fr/stories', to: redirect('fr/alumni')
  get 'en/*path', to: redirect { |path_params, req| path_params[:path] }

  react_exceptions = ["pt-BR", "zh-CN", "es", "ja"]
  react_exceptions.each do | exception |
    get "#{exception.to_s}/react", to: redirect("/react")
  end


  get 'ondemand/*path', to: redirect { |path_params, req| "https://ondemand.lewagon.com/#{req.fullpath.gsub("/ondemand/", "")}" }
  get 'codingstationparis', to: redirect('https://www.meetup.com/fr-FR/Le-Wagon-Paris-Coding-Station')

  {
    'davidverbustel' => 'david-joins-efounders',
    'oliviergodement' => 'olivier-joined-stripe-as-user-ops-lead',
    'amontcoudiol' => 'adrien-and-max-reinvent-tv',
    'olixier' => 'seeding-one-million-with-kudoz',
    'aliceclv' => 'alice-joins-save-as-backend-dev'
  }.each do |github_nickname, new_slug|
    ['', 'fr/'].each do |locale|
      get "#{locale.to_s.underscore}stories/#{github_nickname}", to: redirect("#{locale.to_s.underscore}stories/#{new_slug}")
    end
  end

  constraints(city_constraint) do
    get "apply/(:city)" => "applies#new", locale: :en, as: :apply_en
    get "postuler/(:city)" => "applies#new", locale: :fr, as: :apply_fr
    get "candidatar/(:city)" => "applies#new", locale: :"pt-BR", as: :apply_pt_br
    get "postularse/(:city)" => "applies#new", locale: :es, as: :apply_es
    get "申请/(:city)" => "applies#new", locale: :"zh-CN", as: :apply_zh_cn
    get "アプライ/(:city)" => "applies#new", locale: :ja, as: :apply_ja
    post "apply/(:city)" => "applies#create", as: :apply
    post "apply/validate" => "applies#validate", as: :validate_apply
  end

  get "blog/rss", to: 'posts#rss', defaults: { format: :xml }, as: :rss

  get "hec", to: 'applies#new_hec', as: :new_hec_apply
  post "hec", to: 'applies#create_hec', as: :hec_apply, locale: :fr

  get "edhec", to: 'applies#new_edhec', as: :new_edhec_apply
  post "edhec", to: 'applies#create_edhec', as: :edhec_apply, locale: :fr

  scope "(:locale)", locale: /fr|pt-BR|zh-CN|es|ja/ do
    root to: "pages#home"
    get "faq", to: "pages#show", template: "faq", as: :faq
    get "jobs", to: "pages#show", template: "jobs", as: :jobs
    get "stack", to: "pages#stack", template: "stack", as: :stack
    get "employers", to: "pages#employers", template: "employers", as: :employers
    get "learn-to-code(/:city)", to: "pages#learn", template: "learn", as: :learn
    get "enterprise", to: "pages#enterprise", template: "enterprise", as: :enterprise
    get "blog/videos", to: "posts#videos", template: "videos", as: :videos
    get "blog/all", to: "posts#all", template: "all", as: :all
    get "alumni" => "students#index", as: :alumni
    get "projects" => "projects#index", as: :projects
    get "blog", to: 'posts#index', as: :blog
    get "blog/:slug", to: 'posts#show', as: :post
    get "live", to: 'pages#live', as: :live
    get "shop" => "pages#shop", as: :shop
    get "vae" => "pages#vae", as: :vae
    get "cgv" => "pages#cgv", as: :cgv
    get "react" => "pages#react", locale: :en, as: :react
    get "lemoisducode" => "pages#lemoisducode", as: :lemoisducode
    get "partners" => "pages#partners", as: :partners

    constraints(city_constraint) do
      get ":city" => "cities#show", as: :city
    end
    resources :projects, only: [:show]
    resources :stories, only: [:show]
    resources :students, only: [:show]
    resources :demoday, only: [:index, :show] do
      member do
        get "*product_slug", to: 'demoday#show', as: :with_slug
      end
    end
  end

  resources :subscribes, only: :create

  # API
  resource :cache, only: :destroy

  # SEO
  get 'robots', to: 'pages#robots'

  # Old
  get 'wagon_bar', to: redirect('/fr')

  # Linkedin Token
  get 'linkedin', to: 'pages#linkedin'

  # Sidekiq
  require "sidekiq/web"
  require "sidekiq/cron/web"
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404" => "application#render_404", via: :all
end

# Create helper for static_routes
Rails.application.routes.url_helpers.module_eval do
  STATIC_ROUTES.each do |route, _|
    define_method "#{route}_path".to_sym do |args = {}|
      locale = args[:locale] || :fr
      self.send(:"#{route}_#{locale.to_s.underscore}_path")
    end

    define_method "#{route}_url".to_sym do |args = {}|
      locale = args[:locale] || :fr
      self.send(:"#{route}_#{locale.to_s.underscore}_url")
    end
  end
end

app/models/post.rb
class Post
  include MarkdownArticle

  FILENAME_PATTERN = /\d{4}-\d{2}-\d{2}-(.*)\.md/

  def video?
    layout.to_sym == :video
  end

  def post?
    layout.to_sym == :post
  end

  def story?
    false
  end

  def locale
    metadata[:locale]
  end

  def slug
    @slug ||= (Pathname.new(@file).basename.to_s[FILENAME_PATTERN, 1])
  end

  def date
    @date ||= Date.parse(Pathname.new(@file).basename.to_s[FILENAME_PATTERN, 0])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :hide_drift
  before_action :set_top_bar

  def index
    if request.format.html? || params[:post_page]
      posts = (Post.all + Story.all).sort_by { |p| p.date }.reverse
      @posts = posts.select(&:post?)
      @videos = posts.select(&:video?)
      @stories = posts.select(&:story?)

      if I18n.locale == :fr
        @videos = @videos.select { |m| m.locale == "fr" }
        select_content("fr")
      elsif I18n.locale == :"pt-BR"
        @videos = @videos.select { |m| m.locale == "pt-BR" }
        select_content("en")
      else
        @videos = @videos.select { |m| m.locale == "en" }
        select_content("en")
      end
    end

    if request.format.html?
      @statistics = Kitt::Client.query(Statistics::Query).data.statistics
    end
  end

  def rss
    @posts = (Post.all + Story.all).sort_by { |p| p.date }.reverse
    render layout: false
  end

  def show
    @post = Post.find(params[:slug])
    posts = Post.all
    @videos = (posts.select(&:video?) - [ @post ])
    @posts = (posts.select(&:post?) - [ @post ])

    if I18n.locale == :fr
      @videos = @videos.select { |m| m.locale == "fr" }.sample(2)
      @posts = @posts.select { |m| m.locale == "fr" }.sample(3)
    elsif I18n.locale == :"pt-BR"
      @videos = @videos.select { |m| m.locale == "pt-BR" }.sample(2)
      @posts = @posts.select { |m| m.locale == "en" }.sample(3)
    else
      @videos = @videos.select { |m| m.locale == "en" }.sample(2)
      @posts = @posts.select { |m| m.locale == "en" }.sample(3)
    end
    render_404 if @post.nil?
  end

  def videos
    posts = Post.all
    @videos = posts.select(&:video?)

    if I18n.locale == :fr
      select_video("fr")
    elsif I18n.locale == :"pt-BR"
      select_video("pt-BR")
    else
      select_video("en")
    end
  end

  def all
    posts = (Post.all + Story.all).sort_by { |p| p.date }.reverse
    @posts = posts.select(&:post?)

    if I18n.locale == :fr
      select_post("fr")
    else
      select_post("en")
    end
  end

  private

  def select_content(locale)
    @stories = @stories.select { |m| m.locale == locale }
    @posts = @posts.select { |m| m.locale == locale }
    @posts = Kaminari.paginate_array(@posts).page(params[:post_page]).per(3)
  end

  def select_video(locale)
    @videos = @videos.select { |m| m.locale == locale }
    if params[:category].present?
      @videos = @videos.select { |post| post.labels.include? params[:category] }
    end
    @videos = Kaminari.paginate_array(@videos).page(params[:post_page]).per(6)
  end

  def select_post(locale)
    @posts = @posts.select { |m| m.locale == locale }
    if params[:category].present?
      @posts = @posts.select { |post| post.labels.include? params[:category] }
    end
    @posts = Kaminari.paginate_array(@posts).page(params[:post_page]).per(9)
  end

  def set_top_bar
    if I18n.locale == :fr
      @top_bar_message = I18n.t('.top_bar_podcast_message')
      @top_bar_cta = I18n.t('.top_bar_podcast_cta')
      @top_bar_url = "https://shows.pippa.io/lewagon"
    end
  end

  def hide_drift
    @hide_drift = true
  end
end

app/views/posts/_filter_menu_post.html.erb
<ul>
  <li class="<%= params[:category].blank? ? 'filter-active' : nil %>">
    <%= link_to "All", all_path, remote: true %>
  </li>
  <li class="<%= params[:category] == 'tutorial' ? 'filter-active' : nil %>">
    <%= link_to "Tutorials", all_path(category: 'tutorial'), remote: true %>
  </li>
  <li class="<%= params[:category] == 'alumni' ? 'filter-active' : nil %>">
    <%= link_to "Alumni", all_path(category: 'alumni'), remote: true %>
  </li>
  <li class="<%= params[:category] == 'podcast' ? 'filter-active' : nil %>">
    <%= link_to "Podcasts", all_path(category: 'podcast'), remote: true %>
  </li>
</ul>

app/views/posts/_filter_menu_video.html.erb
<ul>
  <li class="<%= params[:category].blank? ? 'filter-active' : nil %>">
    <%= link_to "All", videos_path, remote: true %>
  </li>
  <li class="<%= params[:category] == 'workshop' ? 'filter-active' : nil %>">
    <%= link_to "Workshops", videos_path(category: 'workshop'), remote: true %>
  </li>
  <li class="<%= params[:category] == 'talk' ? 'filter-active' : nil %>">
    <%= link_to "Talks", videos_path(category: 'talk'), remote: true %>
  </li>
  <li class="<%= params[:category] == 'backstage' ? 'filter-active' : nil %>">
    <%= link_to "Backstage", videos_path(category: 'backstage'), remote: true %>
  </li>
</ul>

app/views/posts/all.html.erb
<% content_for(:title) { t ".posts_title" } %>
<% content_for(:description) { t '.posts_description' } %>
<%= content_for(:image_url) { image_url 'social/all_posts_card.png' } %>

<div class="container breadcrumb">
  <ul>
    <li><%= link_to t('.breadcrumb_1'), blog_path %></li>
    <li><%= t('.breadcrumb_2') %></li>
  </ul>
</div>

<section class="posts">
  <h3 class="section-title"><small><%= t('.posts_small') %></small><%= t('.posts_title') %></h3>

  <div class="filter-container" id="posts-filter-container">
    <%= render "filter_menu_post" %>
  </div>

  <div id="posts-container" class="container">
    <%= render 'more_posts', posts: @posts %>
  </div>

  <div id="paginator">
    <%= link_to_next_page @posts, t(".show_more_posts"), remote: true, param_name: :post_page, id: 'load_more_posts', class: 'more-posts content-cta' %>
  </div>
</section>

app/views/posts/index.html.erb
<% count = 2000 %>
<% if @statistics && @statistics.alumni_count && @statistics.alumni_count.is_a?(Fixnum) %>
  <% count = @statistics.alumni_count %>
<% end %>

<% content_for(:title) { t ".title" } %>
<% content_for(:description) { t '.blog_catchline' } %>
<% content_for(:image_url) { image_url 'social/all_posts_card.png' } %>
<% content_for(:headers) do %>
  <link rel="alternate" type="application/rss+xml" href="<%= rss_url %>" />
<% end %>

<div class="posts">
  <h1><%= t(".blog_title") %><small><%= t(".blog_catchline") %></small></h1>
  <div class="container-fluid blog-header">
    <div class="row">
      <% if @videos && @videos.any? %>
        <div class="col-md-8 col-md-offset-2 header-main">
          <% video = @videos.first %>
          <%= link_to post_path video.slug do %>
            <div class="video-thumbnail" style="background-image: url('https://img.youtube.com/vi/<%= video.youtube_slug %>/maxresdefault.jpg')">
            </div>
          <% end %>
        </div>
      <% end %>

      <% if I18n.locale == :fr %>
        <div class="col-md-8 col-md-offset-2 header-aside aside-podcast">
          <%= link_to "https://shows.pippa.io/lewagon" do %>
            <div class="header-aside-item" style="background-image: url('<%= asset_path "banners/blog-podcast.jpg" %>')">
              <div class="aside-item-thumbnail" style="background-image: url('<%= asset_path "banners/itunes-podcast.jpg" %>')">
              </div>
              <div class="aside-item-content">
                <div>
                  <h3><%= t(".header_aside_3") %></h3>
                  <p><%= t(".header_aside_3_content") %></p>
                </div>
                <ul>
                  <li>Podcast</li>
                  <li>Startup</li>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="col-md-8 col-md-offset-2 header-aside">
        <%= link_to all_path do %>
          <div class="header-aside-item">
            <div class="aside-item-thumbnail" style="background-image: url('<%= asset_path "banners/blog-posts.jpg" %>')">
            </div>
            <div class="aside-item-content">
              <h3><%= t(".header_aside_1") %></h3>
              <ul>
                <li>Tutorials</li>
                <li>Alumni</li>
                <li>Podcasts</li>
              </ul>
            </div>
          </div>
        <% end %>
        <%= link_to videos_path do %>
          <div class="header-aside-item">
            <div class="aside-item-thumbnail" style="background-image: url('<%= asset_path "banners/blog-videos.jpg" %>')">
            </div>
            <div class="aside-item-content">
              <h3><%= t(".header_aside_2") %></h3>
              <ul>
                <li>Workshops</li>
                <li>Talks</li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<section class="posts">
  <h3 class="section-title"><small><%= t(".posts_small") %></small><%= t(".posts_title") %></h3>
  <div id="posts-container" class="container-fluid">
    <%= render 'more_posts', posts: @posts %>
  </div>
  <%= link_to all_path, class: 'content-cta' do %>
    <%= t(".see_all_posts") %>
  <% end %>
</section>

<section class="recorded">
  <h3 class="section-title"><small><%= t(".videos_small") %></small><%= t(".videos_title") %></h3>
  <div class="container-fluid">
    <% @videos && @videos.take(4).each_slice(2) do |videos| %>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="row">
            <% videos.each do |video| %>
              <div class="col-sm-6">
                <%= link_to post_path video.slug do %>
                  <div class="video-thumbnail" style="background-image: url('https://img.youtube.com/vi/<%= video.youtube_slug %>/hqdefault.jpg')">
                    <div class="video-details">
                      <div class="catergory-items">
                        <%= render "shared/flags/#{video.locale_icon}" %>
                        <ul>
                          <% video.labels.each do |tag| %>
                            <li><%= tag %></li>
                          <% end %>
                        </ul>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to videos_path, class: 'content-cta' do %>
      <%= t(".see_all_videos") %>
    <% end %>
  </div>
</section>

<section class="more-content">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <%= link_to alumni_path do %>
          <div class="more-content-thumbnail" style="background-image: url('<%= asset_path "banners/banner-alumni.jpg" %>')">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 52 52" style="enable-background:new 0 0 52 52;" xml:space="preserve" width="512px" height="512px">
              <g>
                <path d="M26,0C11.664,0,0,11.663,0,26s11.664,26,26,26s26-11.663,26-26S40.336,0,26,0z M26,50C12.767,50,2,39.233,2,26   S12.767,2,26,2s24,10.767,24,24S39.233,50,26,50z" fill="#FFFFFF"/>
                <path d="M38.5,25H27V14c0-0.553-0.448-1-1-1s-1,0.447-1,1v11H13.5c-0.552,0-1,0.447-1,1s0.448,1,1,1H25v12c0,0.553,0.448,1,1,1   s1-0.447,1-1V27h11.5c0.552,0,1-0.447,1-1S39.052,25,38.5,25z" fill="#FFFFFF"/>
              </g>
            </svg>
            <div class="content-details">
              <h4><%= t(".more_stories") %></h4>
              <span><%= count %> <%= t(".more_stories_details") %></span>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-sm-6">
        <%= link_to demoday_index_path do %>
          <div class="more-content-thumbnail" style="background-image: url('<%= asset_path "officials/next-demoday.jpg" %>')">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 52 52" style="enable-background:new 0 0 52 52;" xml:space="preserve" width="512px" height="512px">
              <g>
                <path d="M26,0C11.664,0,0,11.663,0,26s11.664,26,26,26s26-11.663,26-26S40.336,0,26,0z M26,50C12.767,50,2,39.233,2,26   S12.767,2,26,2s24,10.767,24,24S39.233,50,26,50z" fill="#FFFFFF"/>
                <path d="M38.5,25H27V14c0-0.553-0.448-1-1-1s-1,0.447-1,1v11H13.5c-0.552,0-1,0.447-1,1s0.448,1,1,1H25v12c0,0.553,0.448,1,1,1   s1-0.447,1-1V27h11.5c0.552,0,1-0.447,1-1S39.052,25,38.5,25z" fill="#FFFFFF"/>
              </g>
            </svg>
            <div class="content-details">
              <h4><%= t(".more_videos") %></h4>
              <span><%= t(".more_videos_details") %></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<%= render partial: "shared/playlist" %>

app/views/posts/show.html.erb
<% content_for(:title) do %>
  <%= @post.title.html_safe %> - Le Wagon
<% end %>

<% content_for(:description) do %>
  <%= @post.description.html_safe %>
<% end %>

<% content_for(:image_url) do %>
  <% if @post.layout.to_sym == :video %>
    https://img.youtube.com/vi/<%= @post.youtube_slug %>/maxresdefault.jpg
  <% else %>
    <%= post_image_url(@post.thumbnail) if @post.thumbnail %>
  <% end %>
<% end %>


<!-- FACEBOOK SDK ON SHOW VIEW -->
<% if @post.layout.to_sym == :video || @post.layout.to_sym == :post %>
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '737501859652485',
      xfbml      : true,
      version    : 'v2.9'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<% end %>

<!-- VIDEO SHOW VIEW -->
<% if @post.layout.to_sym == :video %>
  <div class="container breadcrumb">
    <ul>
      <li><%= link_to t('.breadcrumb_1'), blog_path %></li>
      <li><%= link_to t('.breadcrumb_videos_2'), videos_path %></li>
      <li><%= @post.title.html_safe %></li>
    </ul>
  </div>
  <div style="overflow: hidden;">
    <div class="container video-layout">
      <div class="row">

        <!-- AFFIX - SOCIAL SHARING OPTIONS -->
        <div class="col-md-2">
          <%= render "posts/social_sharing" %>
        </div>

        <!-- CONTENT - VIDEO CONTAINER -->
        <article class="blog-video col-md-8">
          <div class="video-main-wrapper">
            <!-- CONTENT - VIDEO WRAPPER -->
            <div id="video-wrapper" class="video-wrapper">
              <div class="video-container">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.youtube_slug %>?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
              </div>
            </div>
          </div>

          <!-- CONTENT - VIDEO DETAILS -->
          <div class="video-description">
            <div class="video-specs">
              <div class="video-title">
                <h1><%= @post.title %></h1>
              </div>
              <% if @post.content.blank? %>
                <p><%= @post.description  %></p>
              <% else %>
                <%= raw @post.content  %>
              <% end %>
              <span><% if @post.author[:picture] %><%= author_image_tag(@post.author[:picture]) %><% end %>Posted on <%= @post.date.to_date.strftime("%d %b %Y") %> by <%= @post.author[:fname].capitalize %> <%= @post.author[:lname].capitalize %></span>
            </div>
          </div>

          <div class="more-videos">
            <h3 class="section-title"><small><%= t('.watch_more_title') %></small><%= t('.watch_more_catchline') %></h3>
            <div class="row">
              <% @videos.each do |video| %>
                <div class="col-sm-6">
                  <%= link_to post_path video.slug do %>
                    <div class="video-thumbnail" style="background-image: url('https://img.youtube.com/vi/<%= video.youtube_slug %>/maxresdefault.jpg')">
                      <div class="video-details">
                        <div class="catergory-items">
                          <%= render "shared/flags/icon_flag_#{video.locale}" %>
                          <ul>
                            <% video.labels.each do |tag| %>
                              <li><%= tag %></li>
                            <% end %>
                          </ul>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </article>
      </div>
    </div>
  </div>
<% else %>

<!-- POST SHOW VIEW -->
  <div class="container breadcrumb">
    <ul>
      <li><%= link_to t('.breadcrumb_1'), blog_path %></li>
      <li><%= link_to t('.breadcrumb_posts_2'), all_path %></li>
      <li><%= @post.title.html_safe %></li>
    </ul>
  </div>
  <div style="overflow: hidden;">
    <article class="blog-post">
      <div class="post-header" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.6)), url('<%= post_image_url(@post.thumbnail) %>')">

        <h1><%= @post.title.html_safe %></h1>
        <p class="written-by"><% if @post.author[:picture] %><%= author_image_tag(@post.author[:picture]) %><% end %>Published by <%= @post.author[:fname] %> <%= @post.author[:lname] %> on <%= @post.date.to_date.strftime("%d %b %Y") %></p>
      </div>
      <div class="post-wrapper container">
        <div class="row">

          <!-- AFFIX - SOCIAL SHARING OPTIONS -->
          <div class="col-md-2">
            <div data-spy="affix" data-offset-top="620" data-offset-bottom="2300">
              <%= render 'posts/social_sharing' %>
            </div>
          </div>

          <!-- POST - CONTENT -->
          <div class="col-md-8 post-content">
            <%= raw @post.content %>

            <!-- POST - AUTHOR INFO -->
            <% if @post.author %>
              <div class="post-author">
                <% if @post.author[:picture] %>
                  <%= author_image_tag(@post.author[:picture]) %>
                <% end %>
                <div class="author-details">
                  <span class="author-name"><%= @post.author[:fname] %> <%= @post.author[:lname] %></span>
                  <i class="author-position"><%= @post.author[:position] %> at <%= link_to @post.author[:company], "https://www." + @post.author[:company_website].to_s %></i>
                  <p class="author-bio"><%= @post.author[:bio] %></p>
                  <ul class="author-social">
                    <% if @post.author[:instagram] %>
                      <li>
                        <a href="https://www.instagram.com/<%= @post.author[:instagram] %>">
                          <i class="fa fa-instagram" aria-hidden="true"></i>
                        </a>
                      </li>
                    <% end %>
                    <% if @post.author[:twitter] %>
                      <li>
                        <a href="https://www.twitter.com/<%= @post.author[:twitter] %>">
                          <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                      </li>
                    <% end %>
                    <% if @post.author[:linkedin] %>
                      <li>
                        <a href="https://www.linkedin.com/in/<%= @post.author[:linkedin] %>">
                          <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </a>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </article>

    <!-- END - READ MORE POSTS -->
    <div class="container-fluid more-posts">
      <h3 class="section-title"><small><%= t('.read_more_title') %></small><%= t('.read_more_catchline') %></h3>
      <div class="container-fluid">
        <div class="row">
          <% @posts.each do |post| %>
            <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
              <a href="<%= post_path post.slug %>">
                <article class="post-thumbnail">
                  <div class="card-author">
                    <div class="background-author" style="background-image: url('<%= post_image_url(post.thumbnail) %>')"></div>
                    <% if post.author %>
                      <div class="post-author">
                        <% if post.author[:picture] %>
                          <%= author_image_tag(post.author[:picture]) %>
                        <% end %>
                        <div class="author-details">
                          <span class="author-name"><%= post.author[:fname] %> <%= post.author[:lname] %></span>
                          <i class="author-position"><%= post.author[:position] %><br><small>at <%= post.author[:company] %></small></i>
                        </div>
                      </div>
                    <% end %>
                  </div>
                  <div class="card-content">
                    <ul>
                      <% post.labels.each do |tag| %>
                        <li><%= tag %></li>
                      <% end %>
                    </ul>
                    <h2><%= post.title.html_safe %></h2>
                    <% if post.description %>
                      <p class="description"><%= post.description.truncate(260) %></p>
                    <% end %>
                    <span class="read-time">
                      <i class="fa fa-clock-o" aria-hidden="true"></i> <%= post.read_time %> min reading
                      <% if post.date %> - Posted on <%= post.date.to_date.strftime("%d %b %Y") %><% end %>
                    </span>
                  </div>
                </article>
              </a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% content_for(:after_js) do %>
  <script>
    document.getElementById('shareBtn').onclick = function() {
      FB.ui({
        method: 'share',
        display: 'popup',
        href: window.location.href,
      }, function(response){});
    }
  </script>
<% end %>